import { NgModule } from '@angular/core';
import { MatCheckboxModule,
         MatFormFieldModule,
         MatInputModule,
         MatSelectModule,
         MatButtonModule,
         MatSortModule,
         MatCardModule,
         MatTableModule,
         MatTooltipModule,
         MatDialogModule,
         MatIconModule,
         MatSnackBarModule,
         MatDatepickerModule,
         MatTabsModule,
         MatChipsModule,
         MatRadioModule,
         MatExpansionModule,
         MatSidenavModule,
        MatMenuModule,
        MatAutocompleteModule,
        MatPaginatorModule } from '@angular/material';

@NgModule({
  imports: [ MatCheckboxModule,
             MatFormFieldModule,
             MatInputModule,
             MatSelectModule,
             MatButtonModule,
             MatCardModule,
             MatSortModule,
             MatTableModule,
             MatTooltipModule,
             MatSnackBarModule,
             MatDialogModule,
             MatIconModule,
             MatDatepickerModule,
             MatTabsModule,
             MatChipsModule,
             MatRadioModule,
             MatExpansionModule,
             MatSidenavModule,
             MatMenuModule,
            MatAutocompleteModule,
            MatPaginatorModule
        ],
  exports: [ MatCheckboxModule,
             MatSortModule,
             MatFormFieldModule,
             MatInputModule,
             MatSelectModule,
             MatButtonModule,
             MatCardModule,
             MatTableModule,
             MatTooltipModule,
             MatSnackBarModule,
             MatDialogModule,
             MatIconModule,
             MatDatepickerModule,
             MatTabsModule,
             MatChipsModule,
             MatRadioModule,
             MatExpansionModule,
             MatSidenavModule,
             MatMenuModule,
             MatAutocompleteModule,
             MatPaginatorModule
            ],
})
export class MyOwnCustomMaterialModule { }